name: Assert label tested

on:
  workflow_run:
    workflows:
    - Test
    types:
    - completed
  workflow_dispatch:

jobs:

  assert:
    name: Assert label tested
    runs-on: ubuntu-22.04
    steps:

    - name: Test
      #if: "!contains(github.event.pull_request_target.labels.*.name, 'tested')"
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      run: |
        echo "${CONTEXT_GITHUB}"

        if test -z "${PR}"; then
            echo "ERROR: Unable to find PR"
            exit 1
        fi

        echo "The PR is missing label tested"
        exit 1