name: Assert label tested

on:
  pull_request:
    types:
    - labeled
    - reopened
    paths:
    - .github/workflows/test.yml
  pull_request_target:
    types:
    - labeled
    - reopened
    paths:
    - tools/**
  workflow_dispatch:

jobs:

  assert:
    name: Assert label tested
    runs-on: ubuntu-22.04
    steps:

    - name: Test
      if: "!contains(github.event.pull_request_target.labels.*.name, 'tested')"
      run: |
        echo "The PR has not been tested"
        exit 1