name: Assert label tested

on:
  workflow_run:
    workflows:
    - Test
    types:
    - completed
  workflow_dispatch:

jobs:

  assert:
    name: Assert label tested
    runs-on: ubuntu-22.04
    steps:

    - name: Test
      #if: "!contains(github.event.pull_request_target.labels.*.name, 'tested')"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        WORKFLOW_RUN_URL="${{ github.event.workflow_run.url }}"
        echo "Triggering workflow run: ${WORKFLOW_RUN_URL}"

        WORKFLOW_RUN_HEAD_BRANCH="${{ github.event.workflow_run.head_branch }}"
        echo "Workflow run head branch: ${WORKFLOW_RUN_HEAD_BRANCH}"

        PR="$(
            curl -sfH "Authorization: Bearer ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?head=${WORKFLOW_RUN_HEAD_BRANCH}" \
            | jq --raw-output '.[].number'
        )"
        echo "Found PR ${PR}"

        if test -z "${PR}"; then
            echo "ERROR: Unable to find PR"
            exit 1
        fi

        if curl -sfH "Authorization: Bearer $(pp github-nicholasdille)" \
                "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR}/labels" \
                | jq --exit-status '.[].name | select(. == "tested")' >/dev/null; then
            echo "PR ${PR} has label tested"

        else
            echo "PR ${PR} is missing label tested"
            exit 1
        fi