name: ghcr

on:
  push:
    paths:
    - Dockerfile
  workflow_dispatch:

permissions:
  packages: write

jobs:

  test:
    name: ghcr
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request' || ( github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'lgtm') )
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install uniget
      uses: uniget-org/uniget-action@main
      with:
        prefix: helper
        tools: gojq regclient

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}/test:${{ github.sha }}
