name: Test

on:
  pull_request:
    types:
    - synchronize
    - reopened
    paths:
    - .github/workflows/test.yml
  pull_request_target:
    types:
    - synchronize
    - reopened
    paths:
    - tools/**
  workflow_dispatch:

jobs:

  # Use https://github.com/actions/github-script
  labels:
    name: Relabel
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:

    - name: Remove label tested
      if: github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'tested')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.number }}
      run: |
        curl -s -v -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR}/labels/tested
