name: Test on approve

on:
  pull_request_review:
    types:
    - submitted
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    if: github.event.review.state == 'approved'
    steps:

    - name: Test
      env:
        PR: ${{ github.event.pull_request.number }}
      run: |
        echo "Test PR ${PR}"