name: Test

on:
  pull_request:
    types:
    - opened
    - synchronize
    - labeled
    - reopened
    paths:
    - .github/workflows/test.yml
    - tools/**
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: |
        echo "Test"

    # Use https://github.com/actions/github-script
    - name: Add label tested
      if: github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'tested')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.number }}
      run: |
        curl -s -v -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR}/labels \
            -d '{"labels":["tested"]}'
