name: Test on pull_request_target

on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - labeled
    - reopened
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:

    - name: Test
      run: |
        echo "Test"