name: Test

on:
  pull_request_review:
    types:
    - submitted
  workflow_dispatch:

jobs:

  test:
    name: Test
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: |
        echo "Test"
