name: Test on pull_request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - labeled
    - reopened
  workflow_dispatch:

jobs:

  test:
    name: Test on pull_request
    runs-on: ubuntu-22.04
    steps:

    - name: Test
      run: |
        echo "Test"