name: Test

on:
  pull_request:
    types:
    - opened
    - synchronize
    - labeled
    - reopened
    paths:
    - .github/workflows/*
  pull_request_target:
    types:
    - opened
    - synchronize
    - labeled
    - reopened
    paths:
    - tools/**

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request' || ( github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'lgtm') )
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install uniget
      uses: uniget-org/uniget-action@main
      with:
        prefix: helper
        tools: gojq regclient

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: uniget-bot
        password: ${{ secrets.BOT_PACKAGES }}

    - name: Test
      env:
        DOCKER_BUILDKIT: 1
        IS_PR: ${{ github.event_name == 'pull_request' }}
        PR: ${{ github.event.pull_request.number }}
      run: |
        echo "Test"
